spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testApp
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
